language: cpp
compiler: clang
sudo: false
dist: trusty
script:
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake -DCMAKE_GENERATOR_PLATFORM=x64 ..
  - make
addons:
  apt:
    packages:
      - cmake
      - libxrandr-dev
      - libxinerama-dev
      - libxcursor-dev
      - libxi-dev
